apiVersion: apps/v1
kind: Deployment
metadata:
  name: ekshello-frontend
  labels:
    app: ekshello-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ekshello-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ekshello-frontend
    spec:
      containers:
      - image: sebastianhof/ekshello-frontend:latest
        imagePullPolicy: Always
        name: ekshello-frontend
        ports:
        - containerPort: 80
          protocol: TCP